# Generated by Django 5.1.4 on 2024-12-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='약품 이름')),
                ('remain', models.FloatField(verbose_name='잔여량')),
                ('reserved', models.FloatField(verbose_name='예약량')),
                ('usage_history', models.JSONField(default=list, verbose_name='사용 기록')),
                ('recent_use', models.DateField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='내용 설명')),
                ('img', models.ImageField(blank=True, null=True, upload_to='books/images/', verbose_name='이미지')),
            ],
        ),
    ]
