# Generated by Django 5.1.4 on 2024-12-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.TextField(blank=True, default='', verbose_name='태그'),
        ),
    ]
