# Generated by Django 5.1.4 on 2024-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reservation_list',
            field=models.JSONField(default=list, verbose_name='예약 리스트'),
        ),
    ]
