# Generated by Django 5.1.4 on 2025-01-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_reservation_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastewaterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='reserved',
            field=models.FloatField(default=0.0, verbose_name='예약량'),
        ),
    ]
