# Generated by Django 5.1.4 on 2025-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_wastewaterrecord_alter_book_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastewaterrecord',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wastewaterrecord',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
